/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './src/**/*.html',
        './src/**/*.vue',
        './src/**/*.js',
    ],
    darkMode: ['variant', [
        '@media (prefers-color-scheme: dark) { &:not(.light *) }',
        '&:is(.dark *)',
    ]],
    theme: {
        screens: {
            sm: '576px',
            md: '768px',
            lg: '992px',
            xl: '1200px',
        },
        container: {
            center: true,
            padding: {
                DEFAULT: '1.5rem',
                sm: '2rem',
                md: '3rem',
                lg: '0rem',
            },
        },
        fontSize: {
            '5xs': ['0.575rem', '1.4'],
            '4xs': ['0.625rem', '1.6'],
            '3xs': ['0.6875rem', '1.18182'],
            '2xs': ['0.75rem', '1.3333'],
            xs: ['0.8125rem;', '1.38462'],
            sm: ['0.9375rem', '1.3333'],
            base: ['1.0625rem', '1.29412'],
            lg: ['1.125rem', '1.6666'],
            xl: ['1.25rem', '1.25'],
            '2xl': ['1.375rem', '1.27273'],
            '3xl': ['1.75rem', '1.21429'],
            '4xl': ['2.125rem', '1.20588'],
            '5xl': ['3rem', '1.2'],
            '6xl': ['3.75rem', '1.16667'],
            '7xl': ['5rem', '1.2'],
            '8xl': ['5.5rem', '1'],
            '9xl': ['6.5rem', '.92'],
        },
        colors: {
            primary: {
                default: 'var(--ion-color-primary)',
                contrast: 'var(--ion-color-primary-contrast)',
                shade: 'var(--ion-color-primary-shade)',
                tint: 'var(--ion-color-primary-tint)',
            },
            secondary: {
                default: 'var(--ion-color-secondary)',
                contrast: 'var(--ion-color-secondary-contrast)',
                shade: 'var(--ion-color-secondary-shade)',
                tint: 'var(--ion-color-secondary-tint)',
            },
            tertiary: {
                default: 'var(--ion-color-tertiary)',
                contrast: 'var(--ion-color-tertiary-contrast)',
                shade: 'var(--ion-color-tertiary-shade)',
                tint: 'var(--ion-color-tertiary-tint)',
            },
            light: {
                default: 'var(--ion-color-light)',
                contrast: 'var(--ion-color-light-contrast)',
                shade: 'var(--ion-color-light-shade)',
                tint: 'var(--ion-color-light-tint)',
            },
            medium: {
                default: 'var(--ion-color-medium)',
                contrast: 'var(--ion-color-medium-contrast)',
                shade: 'var(--ion-color-medium-shade)',
                tint: 'var(--ion-color-medium-tint)',
            },
            dark: {
                default: 'var(--ion-color-dark)',
                contrast: 'var(--ion-color-dark-contrast)',
                shade: 'var(--ion-color-dark-shade)',
                tint: 'var(--ion-color-dark-tint)',
            },
            card: {
                default: 'var(--ion-background-color, #fff)',
                contrast: 'var(--ion-card-background)'
            },
            success: {
                default: 'var(--ion-color-success)',
                contrast: 'var(--ion-color-success-contrast)',
                shade: 'var(--ion-color-success-shade)',
                tint: 'var(--ion-color-success-tint)',
            },
            warning: {
                default: 'var(--ion-color-warning)',
                contrast: 'var(--ion-color-warning-contrast)',
                shade: 'var(--ion-color-warning-shade)',
                tint: 'var(--ion-color-warning-tint)',
            },
            danger: {
                default: 'var(--ion-color-danger)',
                contrast: 'var(--ion-color-danger-contrast)',
                shade: 'var(--ion-color-danger-shade)',
                tint: 'var(--ion-color-danger-tint)',
            },
            step: {
                50: 'var(--ion-color-step-50)',
                100: 'var(--ion-color-step-100)',
                150: 'var(--ion-color-step-150)',
                200: 'var(--ion-color-step-200)',
                250: 'var(--ion-color-step-250)',
                300: 'var(--ion-color-step-300)',
                350: 'var(--ion-color-step-350)',
                400: 'var(--ion-color-step-400)',
                450: 'var(--ion-color-step-450)',
                500: 'var(--ion-color-step-500)',
                550: 'var(--ion-color-step-550)',
                600: 'var(--ion-color-step-600)',
                650: 'var(--ion-color-step-650)',
                700: 'var(--ion-color-step-700)',
                750: 'var(--ion-color-step-750)',
                800: 'var(--ion-color-step-800)',
                850: 'var(--ion-color-step-850)',
                900: 'var(--ion-color-step-900)',
                950: 'var(--ion-color-step-950)',
            },
        },
    },
    plugins: [
    ],
};
